---
title: "university_cleaning"
author: "Amanda Overbye"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---
```{r}
# Load libraries
library(tidyverse)
library(here)
library(janitor)
library(dplyr)
library(rvest) # For web scraping
library(httr) # For web scraping
library(xml2) # For web scraping
library(future) # For parallel processing
library(furrr)
```


```{r}
# Read in and label hd2023.csv
universities <- read_csv(here('data', 'hd2023.csv'))
towers <- read_csv(here('data', 'towers.csv'))
bells_fl_ga_hi_id_il <- read_csv(here('data', 'Bells_FL_GA_HI_ID_IL.csv'))
bells_co_ct_de_dc <- read_csv(here('data', 'Bells_CO_CT_DE_DC.csv'))
bells_in_states <- read_csv(here('data', 'Bells_In_States.csv'))
bell_tower_locations <- read_csv(here('data', 'Bell_Tower_Locations.csv'))
bells_tn <- read_csv(here('data', 'tennessee_bell_towers.csv'))
bells_in_wy <- read_csv(here('data', 'bell_towers_in_wy.csv'))
```

```{r}
# Select the columns I want and get rid of the ones I dont want
universities_filtered <- universities %>% 
  select(
    UNITID,          # Unique institution ID
    INSTNM,          # Institution name
    CITY,            # City
    STABBR,          # State abbreviation
    ZIP,             # ZIP code
    WEBADDR,         # Institution website
    HLOFFER,         # Highest level of offering
    HDEGOFR1,        # Highest degree offered
    DEGGRANT,        # Degree-granting status
    CARNEGIE,        # Carnegie Classification
    C21BASIC,        # Carnegie Classification 2021: Basic
    C21SZSET,        # Carnegie Classification 2021: Size and Setting
    LATITUDE,        # Latitude
    LONGITUD,        # Longitude
    FIPS,            # FIPS state code
    COUNTYCD,        # FIPS County code
    COUNTYNM,        # County name
    INSTSIZE         # Institution size
  )
```


```{r}
# Separate the 'Country-State' column into 'Country' and 'State'
bells_fl_ga_hi_id_il <- bells_fl_ga_hi_id_il %>%
  separate(`Country-State`, into = c("Country", "State"), sep = " - ")
```

```{r}
# Rename columns
bells_fl_ga_hi_id_il <- bells_fl_ga_hi_id_il %>%
  rename(
    City = Location,
    Location = Description
  )

bells_in_wy <- bells_in_wy %>% 
  rename(Location = Description)
```


```{r}
# Binding bells data

# Merge all datasets
all_bells <- bind_rows(
  bells_fl_ga_hi_id_il,
  bells_co_ct_de_dc,
  bell_tower_locations,
  bells_tn,
  bells_in_states,
  bells_in_wy
)
```

```{r}
# Making sure every bell has USA as the country
all_bells$Country <- "USA"
```

